spring:
  application:
    name: eureka-server
  profiles: end1
server:
  port: 9000

eureka:
  instance:
    hostname: endpoint1
  client:
    service-url:
      # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔
      defaultZone: http://endpoint2:9001/eureka/

---
spring:
  application:
    name: eureka-server
    profiles: end2

server:
  port: 9001

eureka:
  instance:
    hostname: endpoint2
  client:
    service-url:
      # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔
      defaultZone: http://endpoint1:9000/eureka/