// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/quote.proto

package com.gold.protobuf.bean;

public final class Quote {
  private Quote() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QuoteInfoVoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rpc.QuoteInfoVo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string securityId = 1;</code>
     * @return The securityId.
     */
    java.lang.String getSecurityId();
    /**
     * <code>string securityId = 1;</code>
     * @return The bytes for securityId.
     */
    com.google.protobuf.ByteString
        getSecurityIdBytes();

    /**
     * <code>string symbol = 2;</code>
     * @return The symbol.
     */
    java.lang.String getSymbol();
    /**
     * <code>string symbol = 2;</code>
     * @return The bytes for symbol.
     */
    com.google.protobuf.ByteString
        getSymbolBytes();

    /**
     * <code>string exchange = 3;</code>
     * @return The exchange.
     */
    java.lang.String getExchange();
    /**
     * <code>string exchange = 3;</code>
     * @return The bytes for exchange.
     */
    com.google.protobuf.ByteString
        getExchangeBytes();

    /**
     * <code>string bid = 4;</code>
     * @return The bid.
     */
    java.lang.String getBid();
    /**
     * <code>string bid = 4;</code>
     * @return The bytes for bid.
     */
    com.google.protobuf.ByteString
        getBidBytes();

    /**
     * <code>string ask = 5;</code>
     * @return The ask.
     */
    java.lang.String getAsk();
    /**
     * <code>string ask = 5;</code>
     * @return The bytes for ask.
     */
    com.google.protobuf.ByteString
        getAskBytes();
  }
  /**
   * Protobuf type {@code rpc.QuoteInfoVo}
   */
  public static final class QuoteInfoVo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rpc.QuoteInfoVo)
      QuoteInfoVoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QuoteInfoVo.newBuilder() to construct.
    private QuoteInfoVo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QuoteInfoVo() {
      securityId_ = "";
      symbol_ = "";
      exchange_ = "";
      bid_ = "";
      ask_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QuoteInfoVo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QuoteInfoVo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              securityId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              symbol_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              exchange_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              bid_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              ask_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gold.protobuf.bean.Quote.internal_static_rpc_QuoteInfoVo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gold.protobuf.bean.Quote.internal_static_rpc_QuoteInfoVo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gold.protobuf.bean.Quote.QuoteInfoVo.class, com.gold.protobuf.bean.Quote.QuoteInfoVo.Builder.class);
    }

    public static final int SECURITYID_FIELD_NUMBER = 1;
    private volatile java.lang.Object securityId_;
    /**
     * <code>string securityId = 1;</code>
     * @return The securityId.
     */
    @java.lang.Override
    public java.lang.String getSecurityId() {
      java.lang.Object ref = securityId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        securityId_ = s;
        return s;
      }
    }
    /**
     * <code>string securityId = 1;</code>
     * @return The bytes for securityId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSecurityIdBytes() {
      java.lang.Object ref = securityId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        securityId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SYMBOL_FIELD_NUMBER = 2;
    private volatile java.lang.Object symbol_;
    /**
     * <code>string symbol = 2;</code>
     * @return The symbol.
     */
    @java.lang.Override
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      }
    }
    /**
     * <code>string symbol = 2;</code>
     * @return The bytes for symbol.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCHANGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object exchange_;
    /**
     * <code>string exchange = 3;</code>
     * @return The exchange.
     */
    @java.lang.Override
    public java.lang.String getExchange() {
      java.lang.Object ref = exchange_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exchange_ = s;
        return s;
      }
    }
    /**
     * <code>string exchange = 3;</code>
     * @return The bytes for exchange.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExchangeBytes() {
      java.lang.Object ref = exchange_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exchange_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BID_FIELD_NUMBER = 4;
    private volatile java.lang.Object bid_;
    /**
     * <code>string bid = 4;</code>
     * @return The bid.
     */
    @java.lang.Override
    public java.lang.String getBid() {
      java.lang.Object ref = bid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bid_ = s;
        return s;
      }
    }
    /**
     * <code>string bid = 4;</code>
     * @return The bytes for bid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBidBytes() {
      java.lang.Object ref = bid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ASK_FIELD_NUMBER = 5;
    private volatile java.lang.Object ask_;
    /**
     * <code>string ask = 5;</code>
     * @return The ask.
     */
    @java.lang.Override
    public java.lang.String getAsk() {
      java.lang.Object ref = ask_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ask_ = s;
        return s;
      }
    }
    /**
     * <code>string ask = 5;</code>
     * @return The bytes for ask.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAskBytes() {
      java.lang.Object ref = ask_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ask_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(securityId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, securityId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, symbol_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(exchange_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, exchange_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, bid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ask_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, ask_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(securityId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, securityId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, symbol_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(exchange_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, exchange_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, bid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ask_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, ask_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gold.protobuf.bean.Quote.QuoteInfoVo)) {
        return super.equals(obj);
      }
      com.gold.protobuf.bean.Quote.QuoteInfoVo other = (com.gold.protobuf.bean.Quote.QuoteInfoVo) obj;

      if (!getSecurityId()
          .equals(other.getSecurityId())) return false;
      if (!getSymbol()
          .equals(other.getSymbol())) return false;
      if (!getExchange()
          .equals(other.getExchange())) return false;
      if (!getBid()
          .equals(other.getBid())) return false;
      if (!getAsk()
          .equals(other.getAsk())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SECURITYID_FIELD_NUMBER;
      hash = (53 * hash) + getSecurityId().hashCode();
      hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
      hash = (53 * hash) + getSymbol().hashCode();
      hash = (37 * hash) + EXCHANGE_FIELD_NUMBER;
      hash = (53 * hash) + getExchange().hashCode();
      hash = (37 * hash) + BID_FIELD_NUMBER;
      hash = (53 * hash) + getBid().hashCode();
      hash = (37 * hash) + ASK_FIELD_NUMBER;
      hash = (53 * hash) + getAsk().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gold.protobuf.bean.Quote.QuoteInfoVo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gold.protobuf.bean.Quote.QuoteInfoVo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rpc.QuoteInfoVo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rpc.QuoteInfoVo)
        com.gold.protobuf.bean.Quote.QuoteInfoVoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gold.protobuf.bean.Quote.internal_static_rpc_QuoteInfoVo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gold.protobuf.bean.Quote.internal_static_rpc_QuoteInfoVo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gold.protobuf.bean.Quote.QuoteInfoVo.class, com.gold.protobuf.bean.Quote.QuoteInfoVo.Builder.class);
      }

      // Construct using com.gold.protobuf.bean.Quote.QuoteInfoVo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        securityId_ = "";

        symbol_ = "";

        exchange_ = "";

        bid_ = "";

        ask_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gold.protobuf.bean.Quote.internal_static_rpc_QuoteInfoVo_descriptor;
      }

      @java.lang.Override
      public com.gold.protobuf.bean.Quote.QuoteInfoVo getDefaultInstanceForType() {
        return com.gold.protobuf.bean.Quote.QuoteInfoVo.getDefaultInstance();
      }

      @java.lang.Override
      public com.gold.protobuf.bean.Quote.QuoteInfoVo build() {
        com.gold.protobuf.bean.Quote.QuoteInfoVo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gold.protobuf.bean.Quote.QuoteInfoVo buildPartial() {
        com.gold.protobuf.bean.Quote.QuoteInfoVo result = new com.gold.protobuf.bean.Quote.QuoteInfoVo(this);
        result.securityId_ = securityId_;
        result.symbol_ = symbol_;
        result.exchange_ = exchange_;
        result.bid_ = bid_;
        result.ask_ = ask_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gold.protobuf.bean.Quote.QuoteInfoVo) {
          return mergeFrom((com.gold.protobuf.bean.Quote.QuoteInfoVo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gold.protobuf.bean.Quote.QuoteInfoVo other) {
        if (other == com.gold.protobuf.bean.Quote.QuoteInfoVo.getDefaultInstance()) return this;
        if (!other.getSecurityId().isEmpty()) {
          securityId_ = other.securityId_;
          onChanged();
        }
        if (!other.getSymbol().isEmpty()) {
          symbol_ = other.symbol_;
          onChanged();
        }
        if (!other.getExchange().isEmpty()) {
          exchange_ = other.exchange_;
          onChanged();
        }
        if (!other.getBid().isEmpty()) {
          bid_ = other.bid_;
          onChanged();
        }
        if (!other.getAsk().isEmpty()) {
          ask_ = other.ask_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gold.protobuf.bean.Quote.QuoteInfoVo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gold.protobuf.bean.Quote.QuoteInfoVo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object securityId_ = "";
      /**
       * <code>string securityId = 1;</code>
       * @return The securityId.
       */
      public java.lang.String getSecurityId() {
        java.lang.Object ref = securityId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          securityId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string securityId = 1;</code>
       * @return The bytes for securityId.
       */
      public com.google.protobuf.ByteString
          getSecurityIdBytes() {
        java.lang.Object ref = securityId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          securityId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string securityId = 1;</code>
       * @param value The securityId to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        securityId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string securityId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecurityId() {
        
        securityId_ = getDefaultInstance().getSecurityId();
        onChanged();
        return this;
      }
      /**
       * <code>string securityId = 1;</code>
       * @param value The bytes for securityId to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        securityId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object symbol_ = "";
      /**
       * <code>string symbol = 2;</code>
       * @return The symbol.
       */
      public java.lang.String getSymbol() {
        java.lang.Object ref = symbol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          symbol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string symbol = 2;</code>
       * @return The bytes for symbol.
       */
      public com.google.protobuf.ByteString
          getSymbolBytes() {
        java.lang.Object ref = symbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          symbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string symbol = 2;</code>
       * @param value The symbol to set.
       * @return This builder for chaining.
       */
      public Builder setSymbol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        symbol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string symbol = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSymbol() {
        
        symbol_ = getDefaultInstance().getSymbol();
        onChanged();
        return this;
      }
      /**
       * <code>string symbol = 2;</code>
       * @param value The bytes for symbol to set.
       * @return This builder for chaining.
       */
      public Builder setSymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        symbol_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object exchange_ = "";
      /**
       * <code>string exchange = 3;</code>
       * @return The exchange.
       */
      public java.lang.String getExchange() {
        java.lang.Object ref = exchange_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          exchange_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string exchange = 3;</code>
       * @return The bytes for exchange.
       */
      public com.google.protobuf.ByteString
          getExchangeBytes() {
        java.lang.Object ref = exchange_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exchange_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string exchange = 3;</code>
       * @param value The exchange to set.
       * @return This builder for chaining.
       */
      public Builder setExchange(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        exchange_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string exchange = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearExchange() {
        
        exchange_ = getDefaultInstance().getExchange();
        onChanged();
        return this;
      }
      /**
       * <code>string exchange = 3;</code>
       * @param value The bytes for exchange to set.
       * @return This builder for chaining.
       */
      public Builder setExchangeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        exchange_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bid_ = "";
      /**
       * <code>string bid = 4;</code>
       * @return The bid.
       */
      public java.lang.String getBid() {
        java.lang.Object ref = bid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string bid = 4;</code>
       * @return The bytes for bid.
       */
      public com.google.protobuf.ByteString
          getBidBytes() {
        java.lang.Object ref = bid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bid = 4;</code>
       * @param value The bid to set.
       * @return This builder for chaining.
       */
      public Builder setBid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string bid = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBid() {
        
        bid_ = getDefaultInstance().getBid();
        onChanged();
        return this;
      }
      /**
       * <code>string bid = 4;</code>
       * @param value The bytes for bid to set.
       * @return This builder for chaining.
       */
      public Builder setBidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ask_ = "";
      /**
       * <code>string ask = 5;</code>
       * @return The ask.
       */
      public java.lang.String getAsk() {
        java.lang.Object ref = ask_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ask_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ask = 5;</code>
       * @return The bytes for ask.
       */
      public com.google.protobuf.ByteString
          getAskBytes() {
        java.lang.Object ref = ask_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ask_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ask = 5;</code>
       * @param value The ask to set.
       * @return This builder for chaining.
       */
      public Builder setAsk(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ask_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ask = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAsk() {
        
        ask_ = getDefaultInstance().getAsk();
        onChanged();
        return this;
      }
      /**
       * <code>string ask = 5;</code>
       * @param value The bytes for ask to set.
       * @return This builder for chaining.
       */
      public Builder setAskBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ask_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rpc.QuoteInfoVo)
    }

    // @@protoc_insertion_point(class_scope:rpc.QuoteInfoVo)
    private static final com.gold.protobuf.bean.Quote.QuoteInfoVo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gold.protobuf.bean.Quote.QuoteInfoVo();
    }

    public static com.gold.protobuf.bean.Quote.QuoteInfoVo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QuoteInfoVo>
        PARSER = new com.google.protobuf.AbstractParser<QuoteInfoVo>() {
      @java.lang.Override
      public QuoteInfoVo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QuoteInfoVo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QuoteInfoVo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QuoteInfoVo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gold.protobuf.bean.Quote.QuoteInfoVo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QuoteInfoVoListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rpc.QuoteInfoVoList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
     */
    java.util.List<com.gold.protobuf.bean.Quote.QuoteInfoVo> 
        getItemsList();
    /**
     * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
     */
    com.gold.protobuf.bean.Quote.QuoteInfoVo getItems(int index);
    /**
     * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
     */
    java.util.List<? extends com.gold.protobuf.bean.Quote.QuoteInfoVoOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
     */
    com.gold.protobuf.bean.Quote.QuoteInfoVoOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code rpc.QuoteInfoVoList}
   */
  public static final class QuoteInfoVoList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rpc.QuoteInfoVoList)
      QuoteInfoVoListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QuoteInfoVoList.newBuilder() to construct.
    private QuoteInfoVoList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QuoteInfoVoList() {
      items_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QuoteInfoVoList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QuoteInfoVoList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                items_ = new java.util.ArrayList<com.gold.protobuf.bean.Quote.QuoteInfoVo>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(
                  input.readMessage(com.gold.protobuf.bean.Quote.QuoteInfoVo.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gold.protobuf.bean.Quote.internal_static_rpc_QuoteInfoVoList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gold.protobuf.bean.Quote.internal_static_rpc_QuoteInfoVoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gold.protobuf.bean.Quote.QuoteInfoVoList.class, com.gold.protobuf.bean.Quote.QuoteInfoVoList.Builder.class);
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<com.gold.protobuf.bean.Quote.QuoteInfoVo> items_;
    /**
     * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.gold.protobuf.bean.Quote.QuoteInfoVo> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.gold.protobuf.bean.Quote.QuoteInfoVoOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
     */
    @java.lang.Override
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
     */
    @java.lang.Override
    public com.gold.protobuf.bean.Quote.QuoteInfoVo getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
     */
    @java.lang.Override
    public com.gold.protobuf.bean.Quote.QuoteInfoVoOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gold.protobuf.bean.Quote.QuoteInfoVoList)) {
        return super.equals(obj);
      }
      com.gold.protobuf.bean.Quote.QuoteInfoVoList other = (com.gold.protobuf.bean.Quote.QuoteInfoVoList) obj;

      if (!getItemsList()
          .equals(other.getItemsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gold.protobuf.bean.Quote.QuoteInfoVoList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVoList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gold.protobuf.bean.Quote.QuoteInfoVoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gold.protobuf.bean.Quote.QuoteInfoVoList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rpc.QuoteInfoVoList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rpc.QuoteInfoVoList)
        com.gold.protobuf.bean.Quote.QuoteInfoVoListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gold.protobuf.bean.Quote.internal_static_rpc_QuoteInfoVoList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gold.protobuf.bean.Quote.internal_static_rpc_QuoteInfoVoList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gold.protobuf.bean.Quote.QuoteInfoVoList.class, com.gold.protobuf.bean.Quote.QuoteInfoVoList.Builder.class);
      }

      // Construct using com.gold.protobuf.bean.Quote.QuoteInfoVoList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gold.protobuf.bean.Quote.internal_static_rpc_QuoteInfoVoList_descriptor;
      }

      @java.lang.Override
      public com.gold.protobuf.bean.Quote.QuoteInfoVoList getDefaultInstanceForType() {
        return com.gold.protobuf.bean.Quote.QuoteInfoVoList.getDefaultInstance();
      }

      @java.lang.Override
      public com.gold.protobuf.bean.Quote.QuoteInfoVoList build() {
        com.gold.protobuf.bean.Quote.QuoteInfoVoList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gold.protobuf.bean.Quote.QuoteInfoVoList buildPartial() {
        com.gold.protobuf.bean.Quote.QuoteInfoVoList result = new com.gold.protobuf.bean.Quote.QuoteInfoVoList(this);
        int from_bitField0_ = bitField0_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gold.protobuf.bean.Quote.QuoteInfoVoList) {
          return mergeFrom((com.gold.protobuf.bean.Quote.QuoteInfoVoList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gold.protobuf.bean.Quote.QuoteInfoVoList other) {
        if (other == com.gold.protobuf.bean.Quote.QuoteInfoVoList.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gold.protobuf.bean.Quote.QuoteInfoVoList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gold.protobuf.bean.Quote.QuoteInfoVoList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.gold.protobuf.bean.Quote.QuoteInfoVo> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          items_ = new java.util.ArrayList<com.gold.protobuf.bean.Quote.QuoteInfoVo>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.gold.protobuf.bean.Quote.QuoteInfoVo, com.gold.protobuf.bean.Quote.QuoteInfoVo.Builder, com.gold.protobuf.bean.Quote.QuoteInfoVoOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
       */
      public java.util.List<com.gold.protobuf.bean.Quote.QuoteInfoVo> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
       */
      public com.gold.protobuf.bean.Quote.QuoteInfoVo getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
       */
      public Builder setItems(
          int index, com.gold.protobuf.bean.Quote.QuoteInfoVo value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
       */
      public Builder setItems(
          int index, com.gold.protobuf.bean.Quote.QuoteInfoVo.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
       */
      public Builder addItems(com.gold.protobuf.bean.Quote.QuoteInfoVo value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
       */
      public Builder addItems(
          int index, com.gold.protobuf.bean.Quote.QuoteInfoVo value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
       */
      public Builder addItems(
          com.gold.protobuf.bean.Quote.QuoteInfoVo.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
       */
      public Builder addItems(
          int index, com.gold.protobuf.bean.Quote.QuoteInfoVo.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.gold.protobuf.bean.Quote.QuoteInfoVo> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
       */
      public com.gold.protobuf.bean.Quote.QuoteInfoVo.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
       */
      public com.gold.protobuf.bean.Quote.QuoteInfoVoOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
       */
      public java.util.List<? extends com.gold.protobuf.bean.Quote.QuoteInfoVoOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
       */
      public com.gold.protobuf.bean.Quote.QuoteInfoVo.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.gold.protobuf.bean.Quote.QuoteInfoVo.getDefaultInstance());
      }
      /**
       * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
       */
      public com.gold.protobuf.bean.Quote.QuoteInfoVo.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.gold.protobuf.bean.Quote.QuoteInfoVo.getDefaultInstance());
      }
      /**
       * <code>repeated .rpc.QuoteInfoVo items = 1;</code>
       */
      public java.util.List<com.gold.protobuf.bean.Quote.QuoteInfoVo.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.gold.protobuf.bean.Quote.QuoteInfoVo, com.gold.protobuf.bean.Quote.QuoteInfoVo.Builder, com.gold.protobuf.bean.Quote.QuoteInfoVoOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.gold.protobuf.bean.Quote.QuoteInfoVo, com.gold.protobuf.bean.Quote.QuoteInfoVo.Builder, com.gold.protobuf.bean.Quote.QuoteInfoVoOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rpc.QuoteInfoVoList)
    }

    // @@protoc_insertion_point(class_scope:rpc.QuoteInfoVoList)
    private static final com.gold.protobuf.bean.Quote.QuoteInfoVoList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gold.protobuf.bean.Quote.QuoteInfoVoList();
    }

    public static com.gold.protobuf.bean.Quote.QuoteInfoVoList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QuoteInfoVoList>
        PARSER = new com.google.protobuf.AbstractParser<QuoteInfoVoList>() {
      @java.lang.Override
      public QuoteInfoVoList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QuoteInfoVoList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QuoteInfoVoList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QuoteInfoVoList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gold.protobuf.bean.Quote.QuoteInfoVoList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_QuoteInfoVo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_QuoteInfoVo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_QuoteInfoVoList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_QuoteInfoVoList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032src/main/proto/quote.proto\022\003rpc\"]\n\013Quo" +
      "teInfoVo\022\022\n\nsecurityId\030\001 \001(\t\022\016\n\006symbol\030\002" +
      " \001(\t\022\020\n\010exchange\030\003 \001(\t\022\013\n\003bid\030\004 \001(\t\022\013\n\003a" +
      "sk\030\005 \001(\t\"2\n\017QuoteInfoVoList\022\037\n\005items\030\001 \003" +
      "(\0132\020.rpc.QuoteInfoVoB\037\n\026com.gold.protobu" +
      "f.beanB\005Quoteb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rpc_QuoteInfoVo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rpc_QuoteInfoVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_QuoteInfoVo_descriptor,
        new java.lang.String[] { "SecurityId", "Symbol", "Exchange", "Bid", "Ask", });
    internal_static_rpc_QuoteInfoVoList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rpc_QuoteInfoVoList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_QuoteInfoVoList_descriptor,
        new java.lang.String[] { "Items", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
