server:
  port: 10001

spring:
  application:
    name: spring-actuator-prometheus

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: true

logging:
  level:
    root: debug